### ISSUE TITLE
Upload report and slides

### ISSUE THREAD

**Issue by joseabernal** [maxbernal/ICPSA#4]

**Comment by ericpairet** [comment]
I propose work in google docs:

https://docs.google.com/presentation/d/1e02Nha88ndUITfWs5boAJCrfn79bmy7S0gjIi1Uhy4g/edit?usp=sharing

I'll set up the presentation. The invitation to these slides has already been sent.

**Comment by joseabernal** [comment]
We can also use a beamer template. 
[imunam.pdf](https://github.com/maxbernal/ICPSA/files/67791/imunam.pdf)
[BredeleDiapo_master.pdf](https://github.com/maxbernal/ICPSA/files/67792/BredeleDiapo_master.pdf)

**Comment by ericpairet** [comment]
Check out the first draft of the presentation at https://www.overleaf.com

**Comment by joseabernal** [comment]
Presentation is now complete. I'll edit your comment to avoid third-party changes.
